FROM jupyter/pyspark-notebook:spark-3.3.2

USER root
RUN apt-get update && \
    apt-get install -y curl gcc python3-dev && \
    apt-get clean;
RUN pip install \
    python-dotenv==0.20.0
COPY ./.env /opt/app/.env